###
GET http://172.166.1.32:8080/echo/world

###
POST http://172.166.1.32:8080/echo
Content-Type: application/json

{
  "msg": "test"
}

###
GET http://172.166.1.32:8080/schema/echo

###
GET http://172.166.1.32:8080/test

###
POST http://172.166.1.32:8080/echo
Content-Type: application/json

Struct{msg=msg1}
